// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByVPSxLJGRfpuVkrGXUKAMTg-qHfA8pBY',
    appId: '1:491700850358:web:33f7532b7840be3d502017',
    messagingSenderId: '491700850358',
    projectId: 'word-cards-e710f',
    authDomain: 'word-cards-e710f.firebaseapp.com',
    storageBucket: 'word-cards-e710f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Nf5l35v4PA1eOxVD0AUGOJUoImQfl5g',
    appId: '1:491700850358:android:47320580a3d77823502017',
    messagingSenderId: '491700850358',
    projectId: 'word-cards-e710f',
    storageBucket: 'word-cards-e710f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgpoQo0fxNzj6yORX8vvHneOdqLLxn8Q',
    appId: '1:491700850358:ios:ec55f9261a219f63502017',
    messagingSenderId: '491700850358',
    projectId: 'word-cards-e710f',
    storageBucket: 'word-cards-e710f.firebasestorage.app',
    iosBundleId: 'com.example.wordLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgpoQo0fxNzj6yORX8vvHneOdqLLxn8Q',
    appId: '1:491700850358:ios:ec55f9261a219f63502017',
    messagingSenderId: '491700850358',
    projectId: 'word-cards-e710f',
    storageBucket: 'word-cards-e710f.firebasestorage.app',
    iosBundleId: 'com.example.wordLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByVPSxLJGRfpuVkrGXUKAMTg-qHfA8pBY',
    appId: '1:491700850358:web:7673ae6362818648502017',
    messagingSenderId: '491700850358',
    projectId: 'word-cards-e710f',
    authDomain: 'word-cards-e710f.firebaseapp.com',
    storageBucket: 'word-cards-e710f.firebasestorage.app',
  );

}